### ISSUE TITLE
Retrieval results for Flickr8K

### ISSUE THREAD

**Issue by orchidmajumder** [LAION-AI/CLIP_benchmark#48]
Hi, will it be possible for you to check if the `zeroshot_retrieval` results (`image_retrieval_recall@5` and `text_retrieval_recall@5`) for Flickr8k reported [here](https://github.com/LAION-AI/CLIP_benchmark/blob/0e9fbd9c2141cc726ae516f7624c0b1e2b26a263/benchmark/benchmark.csv) are correct or not? 

Based on my evaluation, it seems like the numbers reported for Flick8k are rather `image_retrieval_recall@1` and `text_retrieval_recall@1` when evaluated on the Karpathy test split. 

Here are the results I obtained on this dataset with ViT-B-16 (224x224) OpenCLIP model (`laion400m_e32`):

`{"dataset": "flickr8k", "model": "ViT-B-16", "pretrained": "laion400m_e32", "task": "zeroshot_retrieval", "metrics": {"image_retrieval_recall@5": 0.8575999736785889, "text_retrieval_recall@5": 0.9419999718666077}, "language": "en"}`

The metrics I obtained for `image_retrieval_recall@1` and `text_retrieval_recall@1` are 62.04 and 76.89, which is very close to the numbers linked in the CSV above (62.04 an 76.67). 

Thanks in advance for your help.

**Comment by mehdidc** [comment]
Hi @orchidmajumder, thanks for spotting this ! I realize that  flickr8k  results in the CSV are still computed w.r.t to the full set (40456 examples rather than 1K Karpathy test set) where we were still using the full set for Flickr8K, these need to be updated.
If you use the full set (you can try with  [captions.txt](https://github.com/LAION-AI/CLIP_benchmark/files/10145129/captions.txt) using the option `--annotation_file`), you obtain close results to the CSV.  So it is actually Recall@5, just not the right test set. Will update this.

**Comment by orchidmajumder** [comment]
Thanks a lot for clarifying, resolving the issue.
